# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      choice:
        type: choice
        description: Version bump type (maj.min.pat)
        options:
        - major
        - minor
        - patch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v2
      
      - name: Bump version
        run: node ./scripts/release-flow/create-release.js "${{ github.event.inputs.choice }}"

      - name: Stage, Commit new version
        run: |
            git config --global user.email "create-release@devjump.com"
            git config --global user.name "Create-Release Script"
            git add ./package.json
            git commit -m "Bumped version ${{ github.event.inputs.choice }}"

     
