# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      choice:
        type: choice
        description: Version bump type (maj.min.pat)
        options:
        - patch
        - minor
        - major

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: release
      - uses: actions/setup-node@v2

      - name: Compare version in develop and release
        run: |
            git checkout release
            release_version=$(node ./scripts/release-flow/get-version.js)
            echo "release_version=$release_version" >> $GITHUB_ENV
            git checkout develop
            develop_version=$(node ./scripts/release-flow/get-version.js)
            echo "develop_version=$develop_version" >> $GITHUB_ENV

      - name: Verify version
        if: ${{ env.release_version }} != ${{ env.develop_version }}
        run: |
          echo "Can not create release since release ${{ env.release_version }} has not been finished"
          exit 1

      - name: Bump version, Stage, Commit new version, Push to release
        run: |
            git checkout release
            git pull origin develop
            version=$(node ./scripts/release-flow/create-release.js "${{ github.event.inputs.choice }}")
            git config --global user.email "create-release@devjump.com"
            git config --global user.name "Create-Release Script"
            git add ./package.json
            git commit -m "Bumping position ${{ github.event.inputs.choice }} - new version $version"
            git push origin release


