# This is a basic workflow to help you get started with Actions

name: Finish Release
on:
  workflow_dispatch:

jobs:
 finish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v2

      - name: Merge release into master
        run: |
            git pull
            git checkout master
            git pull origin release

      - name: Push to master
        run: |
            git config --global user.email "finish-release@devjump.com"
            git config --global user.name "Finish-Release Script"
            git push origin master

      - name: Create tag
        run: |
            version=$(node ./scripts/release-flow/finish-release.js)
            echo "version=$version" >> $GITHUB_ENV
            git tag -a "$version" -m "Version $version"
            git push origin "$version"

      - name: Merge master into develop
        run: |
            git checkout develop
            git pull origin master
            git push origin develop

      - name: Trigger Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WORKFLOW_RELEASE_DEPLOY_TEST }}
          event-type: trigger-deploy-event
          client-payload: '{"version": "${{ env.version }}"}'


