# This is a basic workflow to help you get started with Actions

name: Finish Release

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - uses: actions/setup-node@v2

      - name: Merge release into master, Create tag of master, Merge master to develop
        run: |
            git config --global user.email "finish-release@devjump.com"
            git config --global user.name "Finish-Release Script"
            git checkout master
            git pull origin release
            git push origin master
            version=$(node ./scripts/release-flow/finish-release.js "${{ github.event.inputs.choice }}")
            echo $version
            git tag -a "$version" -m "Version $version"
            git push origin "$version"
            git checkout develop
            git pull origin master
            git push origin develop


