# This is a basic workflow to help you get started with Actions

name: Finish Release

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - uses: actions/setup-node@v2
    
      - name: Merge release into master, Create tag of master, Merge master to develop
        run: |
            git checkout release
            version=$(node ./scripts/release-flow/finish-release.js "${{ github.event.inputs.choice }}")
            echo $version
            # git config --global user.email "create-release@devjump.com"
            # git config --global user.name "Create-Release Script"
            # git add ./package.json
            # git commit -m "Bumping position ${{ github.event.inputs.choice }} - new version $version"
            # git push origin release

     
